<a href="https://colab.research.google.com/github/AmritttSingh/PyTorch_Tutorial/blob/main/_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
 my_list = [[1,2,3,4,5],[6,7,8,9,10]]
 my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
np1= np.random.rand(3,4)
np1

array([[0.21002673, 0.46374794, 0.32018719, 0.83141551],
       [0.71029939, 0.73074192, 0.33282702, 0.19870946],
       [0.15077456, 0.61067627, 0.32833123, 0.91146126]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.2826,  1.8538, -0.4798, -0.1848],
        [ 0.6317, -0.3357,  0.7478, -1.2523],
        [-1.9556,  0.2722, -0.1278, -0.1459]])

In [8]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.3944, -0.6896, -0.8038, -1.3107],
         [-0.5716,  1.9820, -0.1271,  0.8687],
         [ 3.0792, -0.1261, -0.5248, -0.5763]],

        [[-1.0759, -0.2172,  2.9723,  1.1886],
         [ 0.5979,  0.0185,  1.0240,  1.6649],
         [-0.6999, -0.8366,  0.0209,  0.9615]]])

In [9]:
#create tensor out of np array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2100, 0.4637, 0.3202, 0.8314],
        [0.7103, 0.7307, 0.3328, 0.1987],
        [0.1508, 0.6107, 0.3283, 0.9115]], dtype=torch.float64)