<a href="https://colab.research.google.com/github/AmritttSingh/PyTorch_Tutorial/blob/main/_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#sub
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [10]:
#torch.add(tensor_a,tensor_b)
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [ ]:
#same way for mul,div,remainder,pow